// Code generated by protoc-gen-vkit. DO NOT EDIT.
// versions:
// - protoc-gen-vkit v1.0.0

package handler

import (
	"github.com/visonlv/go-vkit/grpcx"
	
)

func GetList() []interface{} {
	list := make([]interface{}, 0)
	list = append(list, &AuthService{})
	list = append(list, &UserService{})
	
	return list
}

func GetApiEndpoint() []*grpcx.ApiEndpoint {
	return []*grpcx.ApiEndpoint{
		{
			Method:"AuthService.Login",
			Url:"/rpc/vkit-example/AuthService.Login", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"AuthService.Logout",
			Url:"/rpc/vkit-example/AuthService.Logout", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"UserService.Add",
			Url:"/rpc/vkit-example/UserService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"UserService.Update",
			Url:"/rpc/vkit-example/UserService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"UserService.Page",
			Url:"/rpc/vkit-example/UserService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"UserService.Del",
			Url:"/rpc/vkit-example/UserService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"UserService.Get",
			Url:"/rpc/vkit-example/UserService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},
	}
}
